on: push
jobs:
  build:
    runs-on: windows-latest
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    steps:
    - run: dotnet --list-sdks
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.x
    - run: dotnet --list-sdks
    - run: dotnet build
